update_fastlane

default_platform(:ios)

platform :ios do
  desc "Download and install certificates"
  lane :certificates do
    match(
      app_identifier: ["no.agens.Covid19"], 
      username: "ios-enterprise@agens.no",
      type: "development",
      readonly: is_ci,
      git_url: "git@bitbucket.org:agens/ios-certificates-agens-enterprise.git"
    )
  end
end
