update_fastlane

default_platform(:ios)

platform :ios do
  desc "Download and install certificates"
  lane :certificates do
    setup_ci

    match(
      app_identifier: ["no.agens.covid19"], 
      username: "ios-enterprise@agens.no",
      type: "enterprise",
      readonly: is_ci,
      git_url: "git@bitbucket.org:agens/ios-certificates-agens-enterprise.git",
    )

    match(
      app_identifier: ["no.agens.covid19"], 
      username: "ios-enterprise@agens.no",
      type: "development",
      readonly: is_ci,
      git_url: "git@bitbucket.org:agens/ios-certificates-agens-enterprise.git",
    )

    match(
      app_identifier: ["no.agens.covid19.appstore"], 
      username: "ios-dev@agens.no",
      type: "appstore",
      readonly: is_ci,
      git_url: "git@bitbucket.org:agens/ios-certificates-agens.git",
    )

  end

  lane :cultivate do
    update_xcconfig_value(
      path: 'Config.xcconfig',
      name: 'APPCENTER_SECRET',
      value: ENV["APPCENTER_SECRET"]
    )
  end

  lane  :upload_appcenter do
    setup_ci

    gym(
      workspace: "./Covid19.xcworkspace",
      configuration: "Release",
      export_method: "enterprise",
    )

    appcenter_upload(notify_testers: true)
  end


  
end
